TAP version 13
1..4
#          test_collector: test started
not ok 2 - test_collector (FAILED) # collector in dtester/test.py
#          test_failure: test started
not ok 3 - test_failure (FAILED) # intentional failure in dtester/dtests.py
#          test_success: test started
ok 1     - test_success: a test that succeeds
# test_suite: nothing to set up
#          test_single_dep: test started
ok 4     - test_single_dep: one dependency test
# test_suite: nothing to tear down
# Run 4 tests: 2 succeeded 2 failed.
