        test_collector: test started
FAILED  test_collector - collector in dtester/test.py:310
        test_failure: test started
FAILED  test_failure - intentional failure in dtester/dtests.py:48
        test_success: test started
OK      test_success: a test that succeeds
        test_suite: test started
OK      test_suite: a test that succeeds
SKIPPED test_single_dep
Run 5 tests: 2 succeeded 3 failed.
